### ISSUE TITLE
Installation for detectron2 fails when using pytorch 1.6.0+cu101

### ISSUE THREAD

**Issue by jellyheadandrew** [xiexh20/CHORE#10]
Hi, thanks for the great work. I am trying to run the demo but am failing since the installation process you have provided doesn't work.
When running `pip install -r requirements.txt` with torch version 1.6.0, I face this error:

'''''''''''''''''''''''''''''''''''''Error'''''''''''''''''''''''''''''''''''''
Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-req-build-ri2eeos8
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-req-build-ri2eeos8
  Resolved https://github.com/facebookresearch/detectron2.git to commit 3c7bb714795edc7a96c9a1a6dd83663ecd293e36
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-ri2eeos8/setup.py", line 14, in <module>
          assert torch_ver >= [1, 8], "Requires PyTorch >= 1.8"
      AssertionError: Requires PyTorch >= 1.8
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
'''''''''''''''''''''''''''''''''''''Error'''''''''''''''''''''''''''''''''''''

How exactly did you install Detectron2? Can you provide the exact installation procedure?

**Comment by jellyheadandrew** [comment]
Nvm, I was my mistake
